```{r working with date formats}
CEST <- gsub("[- :]", "_", Sys.time())
print(gsub("\\..*", "", CEST))
```
```{r 2024_06_27_11_19_49}
2024_06_27_11_19_49 <- "MITGLIEDER
PORTAL
HOME PROFIL DIENSTE DOKUMENTE SGB IV 23C ABWESENHEIT DOWNLOADS
Dienstsuche Suchaufträge Dienstwünsche Dienstangebote Geplant Abgeschlossen
Dr. med. G. Schleifer
Mitglied Nr.: 16108
  
DIENSTSUCHE
 QUALIFIKATION
 GEWÜNSCHTER ORT
+ 100 km
 AUSGEWÄHLTE VORAUSSETZUNGEN
	Angestelltenverhältnis oder Praxisniederlassung nach § 23c SGB IV
	Masern-Impfschutz gemäß Gesetz
	Berufshaftpflichtversicherung
	Immunitätsnachweis COVID-19
	eigene Schutzausrüstung (Jacke, Pulli, Hose, S3-Schuhe)
	max 24 Stunden am Stück
JUNE 2024
AbwesenheitDienstwunsch
Ergebnis: 3 DiensteSortierung nach: 
Entfernung
NEF NÄHE ENGELSKIRCHEN
2024-2449 in 40 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 28/06/2024
Beginn: 08:00 UhrDauer:
24 h 0 minEnde:
08:00 Uhr
Honorar: 60 €/h
gutes Free WiFi	TV im Arztzimmer	Schreibtisch im Arztzimmer	gemeinsame Küche	Kantine/Cafeteria	gemeinsame Sanitäreinrichtung
gutes Free WiFi	TV im Arztzimmer	Schreibtisch im Arztzimmer	gemeinsame Küche	Kantine/Cafeteria	gemeinsame Sanitäreinrichtung
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVFOBI: GES. PFLICHTFORTBILDUNGEN GEM. § 5 ABS. 4 RETTG NRWMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Denise Reko
NAW NÄHE KOTTENHEIM
2024-2728 in 48 km Entfernung
(Bereits dort gearbeitet)Nichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 30/06/2024
Beginn: 09:00 UhrDauer:
22 h 30 minEnde:
07:30 Uhr
Honorar: 40 €/h + + 25,00 € pro Einsatz
TV im Arztzimmer	Schreibtisch im Arztzimmer	Kochnische mit Wasserkocher/Mikrowelle	eigenes Waschbecken, eigene Toilette und eigene Dusche
TV im Arztzimmer	Schreibtisch im Arztzimmer	Kochnische mit Wasserkocher/Mikrowelle	eigenes Waschbecken, eigene Toilette und eigene Dusche
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Angelik Schmidt
NEF NÄHE UNNA
2024-2552 in 99 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 28/06/2024
Beginn: 08:00 UhrDauer:
8 h 0 minEnde:
16:00 Uhr
Honorar: 70 €/h
eigene Küche
eigene Küche
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVEIGENE SCHUTZAUSRÜSTUNG (JACKEPULLIHOSES3-SCHUHE)FOBI: GES. PFLICHTFORTBILDUNGEN GEM. § 5 ABS. 4 RETTG NRWMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Katharina Koch
AGB
Impressum
Datenschutzerklärung
Notarzt-Börse
Dr. med. André Kröncke e.K.
Erlenhof, Alte Salzstr. 7
23911 Pogeez
 
Telefon: 04541 / 80180-0
Fax: 04541 / 80180-55
E-Mail: service@notarzt-boerse.de"
```
```{r 2024_06_25_05_21_5}
2024_06_25_05_21_58 <- "MITGLIEDER
PORTAL
HOME PROFIL DIENSTE DOKUMENTE SGB IV 23C ABWESENHEIT DOWNLOADS
Dienstsuche Suchaufträge Dienstwünsche Dienstangebote Geplant Abgeschlossen
Dr. med. G. Schleifer
Mitglied Nr.: 16108
  
DIENSTSUCHE
 QUALIFIKATION
 GEWÜNSCHTER ORT
+ 100 km
 AUSGEWÄHLTE VORAUSSETZUNGEN
	Angestelltenverhältnis oder Praxisniederlassung nach § 23c SGB IV
	Masern-Impfschutz gemäß Gesetz
	Berufshaftpflichtversicherung
	Immunitätsnachweis COVID-19
	eigene Schutzausrüstung (Jacke, Pulli, Hose, S3-Schuhe)
	max 24 Stunden am Stück
JUNE 2024
AbwesenheitDienstwunsch
Ergebnis: 2 DiensteSortierung nach: 
Entfernung
NAW NÄHE KOTTENHEIM
2024-2728 in 48 km Entfernung
(Bereits dort gearbeitet)Nichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 30/06/2024
Beginn: 09:00 UhrDauer:
22 h 30 minEnde:
07:30 Uhr
Honorar: 40 €/h + + 25,00 € pro Einsatz
TV im Arztzimmer	Schreibtisch im Arztzimmer	Kochnische mit Wasserkocher/Mikrowelle	eigenes Waschbecken, eigene Toilette und eigene Dusche
TV im Arztzimmer	Schreibtisch im Arztzimmer	Kochnische mit Wasserkocher/Mikrowelle	eigenes Waschbecken, eigene Toilette und eigene Dusche
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Angelik Schmidt
NAW NÖRDLICH VON OLPE
2024-2659 in 64 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 28/06/2024
Beginn: 16:00 UhrDauer:
17 h 0 minEnde:
09:00 Uhr
Honorar: 35 €/h
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Celine Hassel
AGB
Impressum
Datenschutzerklärung
Notarzt-Börse
Dr. med. André Kröncke e.K.
Erlenhof, Alte Salzstr. 7
23911 Pogeez
 
Telefon: 04541 / 80180-0
Fax: 04541 / 80180-55
E-Mail: service@notarzt-boerse.de"
```
```{r Tue Jun 18 05:28:46 2024}
18_06_05_28 <- "MITGLIEDER
PORTAL
HOME PROFIL DIENSTE DOKUMENTE SGB IV 23C ABWESENHEIT DOWNLOADS
Dienstsuche Suchaufträge Dienstwünsche Dienstangebote Geplant Abgeschlossen
Dr. med. G. Schleifer
Mitglied Nr.: 16108
  
DIENSTSUCHE
 QUALIFIKATION
 GEWÜNSCHTER ORT
+ 100 km
 AUSGEWÄHLTE VORAUSSETZUNGEN
	Angestelltenverhältnis oder Praxisniederlassung nach § 23c SGB IV
	Masern-Impfschutz gemäß Gesetz
	Berufshaftpflichtversicherung
	Immunitätsnachweis COVID-19
	eigene Schutzausrüstung (Jacke, Pulli, Hose, S3-Schuhe)
	max 24 Stunden am Stück
JUNE 2024
AbwesenheitDienstwunsch
Ergebnis: 7 DiensteSortierung nach: 
Entfernung
NEF NÄHE ALTENKIRCHEN
2024-2641 in 20 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 24/06/2024
Beginn: 08:00 UhrDauer:
24 h 0 minEnde:
08:00 Uhr
Honorar: 45 €/h
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Katharina Koch
NEF NÄHE RUPPICHTEROTH
2024-2426 in 33 km Entfernung
(Bereits dort gearbeitet)Nichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 19/06/2024
Beginn: 19:45 UhrDauer:
12 h 0 minEnde:
07:45 Uhr
Honorar: 50 €/h
TV im Arztzimmer	Schreibtisch im Arztzimmer	gemeinsame Küche	Kantine/Cafeteria	eigenes Waschbecken und eigene Toilette
TV im Arztzimmer	Schreibtisch im Arztzimmer	gemeinsame Küche	Kantine/Cafeteria	eigenes Waschbecken und eigene Toilette
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVFOBI: GES. PFLICHTFORTBILDUNGEN GEM. § 5 ABS. 4 RETTG NRWMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Katharina Koch
NEF NÄHE DATTELN
2024-2271 in 34 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 26/06/2024
Beginn: 08:00 UhrDauer:
24 h 0 minEnde:
08:00 Uhr
Honorar: 45 €/h
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVMAX 24 STUNDEN AM STÜCKMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Celine Hassel
FA ANÄSTHESIE NÄHE HEMER
2024-2201 in 86 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 21/06/2024
Beginn: 16:00 UhrDauer:
16 h 0 minEnde:
08:00 Uhr
Arbeitsentgelt: 115,00 € pro Stunde im Tagdienst/85,00 € pro Stunde im Bereitschaftsdienst
gemeinsame Küche	Kantine/Cafeteria	eigenes Waschbecken
gemeinsame Küche	Kantine/Cafeteria	eigenes Waschbecken
Voraussetzungen:KURZFRISTIGES ANSTELLUNGSVERHÄLTNISFACHARZT ANÄSTHESIEMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Denise Reko
NEF NÄHE WINTERBERG
2024-2273 in 90 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 21/06/2024
Beginn: 08:00 UhrDauer:
12 h 0 minEnde:
20:00 Uhr
Honorar: 50 €/h
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVZB NOTFALLMEDIZINMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Luca Raygrotzki
NAW NÄHE HERNE
2024-2609 in 95 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 27/06/2024
Beginn: 08:00 UhrDauer:
12 h 0 minEnde:
20:00 Uhr
Honorar: 50 €/h
TV im Arztzimmer	Schreibtisch im Arztzimmer	Kantine/Cafeteria	eigenes Waschbecken, eigene Toilette und eigene Dusche
TV im Arztzimmer	Schreibtisch im Arztzimmer	Kantine/Cafeteria	eigenes Waschbecken, eigene Toilette und eigene Dusche
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVBERUFSHAFTPFLICHTVERSICHERUNGNACHWEIS KRANKENVERSICHERUNG / PFLEGEVERSICHERUNGNACHWEIS DER DRV-BEFREIUNGMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Kim-Naomi Feindt
DIENSTPLAN NEF DORSTEN JUNI 2024
2024-1759 in 99 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 19/06/2024
Beginn: 16:00 UhrDauer:
16 h 0 minEnde:
08:00 Uhr
Honorar: 50 €/h
TV im Arztzimmer	Schreibtisch im Arztzimmer	Kochnische mit Wasserkocher/Mikrowelle	Kantine/Cafeteria	eigenes Waschbecken, eigene Toilette und eigene Dusche
TV im Arztzimmer	Schreibtisch im Arztzimmer	Kochnische mit Wasserkocher/Mikrowelle	Kantine/Cafeteria	eigenes Waschbecken, eigene Toilette und eigene Dusche
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVBERUFSHAFTPFLICHTVERSICHERUNGEIGENE SCHUTZAUSRÜSTUNG (JACKEPULLIHOSES3-SCHUHE)MASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Miriam Prüß
AGB
Impressum
Datenschutzerklärung
Notarzt-Börse
Dr. med. André Kröncke e.K.
Erlenhof, Alte Salzstr. 7
23911 Pogeez
 
Telefon: 04541 / 80180-0
Fax: 04541 / 80180-55
E-Mail: service@notarzt-boerse.de
`"
```
```{r "Thu Jun 20 18:44:59 2024"}
20_08_18_44 <- "MITGLIEDER
PORTAL
HOME PROFIL DIENSTE DOKUMENTE SGB IV 23C ABWESENHEIT DOWNLOADS
Dienstsuche Suchaufträge Dienstwünsche Dienstangebote Geplant Abgeschlossen
Dr. med. G. Schleifer
Mitglied Nr.: 16108
  
DIENSTSUCHE
 QUALIFIKATION
 GEWÜNSCHTER ORT
+ 100 km
 AUSGEWÄHLTE VORAUSSETZUNGEN
	Angestelltenverhältnis oder Praxisniederlassung nach § 23c SGB IV
	Masern-Impfschutz gemäß Gesetz
	Berufshaftpflichtversicherung
	Immunitätsnachweis COVID-19
	eigene Schutzausrüstung (Jacke, Pulli, Hose, S3-Schuhe)
	max 24 Stunden am Stück
JUNE 2024
AbwesenheitDienstwunsch
Ergebnis: 2 DiensteSortierung nach: 
Entfernung
NEF NÄHE DATTELN
2024-2271 in 34 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 26/06/2024
Beginn: 08:00 UhrDauer:
24 h 0 minEnde:
08:00 Uhr
Honorar: 45 €/h
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVMAX 24 STUNDEN AM STÜCKMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Celine Hassel
NAW NÖRDLICH VON OLPE
2024-2659 in 64 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 28/06/2024
Beginn: 16:00 UhrDauer:
17 h 0 minEnde:
09:00 Uhr
Honorar: 35 €/h
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Celine Hassel
AGB
Impressum
Datenschutzerklärung
Notarzt-Börse
Dr. med. André Kröncke e.K.
Erlenhof, Alte Salzstr. 7
23911 Pogeez
 
Telefon: 04541 / 80180-0
Fax: 04541 / 80180-55
E-Mail: service@notarzt-boerse.de"
```
```{r "Sat Jun 22 08:11:36 2024"}
22_06_22_08 <- "MITGLIEDER
PORTAL
HOME PROFIL DIENSTE DOKUMENTE SGB IV 23C ABWESENHEIT DOWNLOADS
Dienstsuche Suchaufträge Dienstwünsche Dienstangebote Geplant Abgeschlossen
Dr. med. G. Schleifer
Mitglied Nr.: 16108
  
DIENSTSUCHE
 QUALIFIKATION
 GEWÜNSCHTER ORT
+ 100 km
 AUSGEWÄHLTE VORAUSSETZUNGEN
	Angestelltenverhältnis oder Praxisniederlassung nach § 23c SGB IV
	Masern-Impfschutz gemäß Gesetz
	Berufshaftpflichtversicherung
	Immunitätsnachweis COVID-19
	eigene Schutzausrüstung (Jacke, Pulli, Hose, S3-Schuhe)
	max 24 Stunden am Stück
JUNE 2024
AbwesenheitDienstwunsch
Ergebnis: 4 DiensteSortierung nach: 
Entfernung
NEF NÄHE DATTELN
2024-2271 in 34 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 26/06/2024
Beginn: 08:00 UhrDauer:
24 h 0 minEnde:
08:00 Uhr
Honorar: 45 €/h
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVMAX 24 STUNDEN AM STÜCKMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Celine Hassel
NEF NÄHE ENGELSKIRCHEN
2024-2713 in 40 km Entfernung
(Bereits dort gearbeitet)Nichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 23/06/2024
Beginn: 06:47 UhrDauer:
12 h 0 minEnde:
18:47 Uhr
Honorar: 70 €/h
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVFOBI: GES. PFLICHTFORTBILDUNGEN GEM. § 5 ABS. 4 RETTG NRWMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Janina Heindl
DIENSTPLAN SEKUNDÄRTRANSPORTE NORD JUNI 2024
2024-1647 in 64 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 25/06/2024
Beginn: 08:00 UhrDauer:
24 h 0 minEnde:
08:00 Uhr
Honorar: 20 €/h + 50,00 €/Einsatz-Std.
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVBERUFSHAFTPFLICHTVERSICHERUNGGERÄTEPASS / GERÄTEEINWEISUNGMAX 24 STUNDEN AM STÜCKFOBI: GES. PFLICHTFORTBILDUNGEN GEM. § 5 ABS. 4 RETTG NRWGESUNDHEITLICHE UND KÖRPERLICHE EIGNUNG GEM. § 4 ABS. 2 RETTG NRWMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Bianca Fokuhl
NAW NÖRDLICH VON OLPE
2024-2659 in 64 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 28/06/2024
Beginn: 16:00 UhrDauer:
17 h 0 minEnde:
09:00 Uhr
Honorar: 35 €/h
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Celine Hassel
AGB
Impressum
Datenschutzerklärung
Notarzt-Börse
Dr. med. André Kröncke e.K.
Erlenhof, Alte Salzstr. 7
23911 Pogeez
 
Telefon: 04541 / 80180-0
Fax: 04541 / 80180-55
E-Mail: service@notarzt-boerse.de"
```
```{r Sun_Jun_23_07_12_54_2024}
Sun_Jun_23_07_12_54_2024 <- "
MITGLIEDER
PORTAL
HOME PROFIL DIENSTE DOKUMENTE SGB IV 23C ABWESENHEIT DOWNLOADS
Dienstsuche Suchaufträge Dienstwünsche Dienstangebote Geplant Abgeschlossen
Dr. med. G. Schleifer
Mitglied Nr.: 16108
  
DIENSTSUCHE
 QUALIFIKATION
 GEWÜNSCHTER ORT
+ 100 km
 AUSGEWÄHLTE VORAUSSETZUNGEN
	Angestelltenverhältnis oder Praxisniederlassung nach § 23c SGB IV
	Masern-Impfschutz gemäß Gesetz
	Berufshaftpflichtversicherung
	Immunitätsnachweis COVID-19
	eigene Schutzausrüstung (Jacke, Pulli, Hose, S3-Schuhe)
	max 24 Stunden am Stück
JUNE 2024
AbwesenheitDienstwunsch
Ergebnis: 2 DiensteSortierung nach: 
Entfernung
DIENSTPLAN SEKUNDÄRTRANSPORTE NORD JUNI 2024
2024-1647 in 64 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 25/06/2024
Beginn: 08:00 UhrDauer:
24 h 0 minEnde:
08:00 Uhr
Honorar: 20 €/h + 50,00 €/Einsatz-Std.
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVBERUFSHAFTPFLICHTVERSICHERUNGGERÄTEPASS / GERÄTEEINWEISUNGMAX 24 STUNDEN AM STÜCKFOBI: GES. PFLICHTFORTBILDUNGEN GEM. § 5 ABS. 4 RETTG NRWGESUNDHEITLICHE UND KÖRPERLICHE EIGNUNG GEM. § 4 ABS. 2 RETTG NRWMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Bianca Fokuhl
NAW NÖRDLICH VON OLPE
2024-2659 in 64 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 28/06/2024
Beginn: 16:00 UhrDauer:
17 h 0 minEnde:
09:00 Uhr
Honorar: 35 €/h
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Celine Hassel
AGB
Impressum
Datenschutzerklärung
Notarzt-Börse
Dr. med. André Kröncke e.K.
Erlenhof, Alte Salzstr. 7
23911 Pogeez
 
Telefon: 04541 / 80180-0
Fax: 04541 / 80180-55
E-Mail: service@notarzt-boerse.de"
```
```{r 2024_06_24_07_27_00}
2024_06_24_07_27_00 <- "MITGLIEDER
PORTAL
HOME PROFIL DIENSTE DOKUMENTE SGB IV 23C ABWESENHEIT DOWNLOADS
Dienstsuche Suchaufträge Dienstwünsche Dienstangebote Geplant Abgeschlossen
Dr. med. G. Schleifer
Mitglied Nr.: 16108
  
DIENSTSUCHE
 QUALIFIKATION
 GEWÜNSCHTER ORT
+ 100 km
 AUSGEWÄHLTE VORAUSSETZUNGEN
	Angestelltenverhältnis oder Praxisniederlassung nach § 23c SGB IV
	Masern-Impfschutz gemäß Gesetz
	Berufshaftpflichtversicherung
	Immunitätsnachweis COVID-19
	eigene Schutzausrüstung (Jacke, Pulli, Hose, S3-Schuhe)
	max 24 Stunden am Stück
JUNE 2024
AbwesenheitDienstwunsch
Ergebnis: 2 DiensteSortierung nach: 
Entfernung
DIENSTPLAN SEKUNDÄRTRANSPORTE NORD JUNI 2024
2024-1647 in 64 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 25/06/2024
Beginn: 08:00 UhrDauer:
24 h 0 minEnde:
08:00 Uhr
Honorar: 20 €/h + 50,00 €/Einsatz-Std.
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVBERUFSHAFTPFLICHTVERSICHERUNGGERÄTEPASS / GERÄTEEINWEISUNGMAX 24 STUNDEN AM STÜCKFOBI: GES. PFLICHTFORTBILDUNGEN GEM. § 5 ABS. 4 RETTG NRWGESUNDHEITLICHE UND KÖRPERLICHE EIGNUNG GEM. § 4 ABS. 2 RETTG NRWMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Bianca Fokuhl
NAW NÖRDLICH VON OLPE
2024-2659 in 64 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 28/06/2024
Beginn: 16:00 UhrDauer:
17 h 0 minEnde:
09:00 Uhr
Honorar: 35 €/h
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Celine Hassel
AGB
Impressum
Datenschutzerklärung
Notarzt-Börse
Dr. med. André Kröncke e.K.
Erlenhof, Alte Salzstr. 7
23911 Pogeez
 
Telefon: 04541 / 80180-0
Fax: 04541 / 80180-55
E-Mail: service@notarzt-boerse.de"
```
```{r doctary 2024_06_24_07_27_00}
2024_06_24_07_27_00 <- "doctari-portal
Dashboard
Jobbörse
Einsätze
Profil
GS
Grigorij Schleifer
Stellenangebote
Alle
Empfohlene Jobs
Beworben
2 Ergebnisse

Fachrichtung

Anästhesiologie

Zusatzbezeichnung
Notfallmedizin


Bitte auswählen

Arbeitsmodell
Mehr Infos

Flexible Zeitarbeit

Einsatzbereiche
Normalstation

Intensivbereich

OP-Bereich

Funktionsbereich

Nicht-akutklinischer Bereich


Bitte auswählen
Oberbereich
Herz-Thoraxchirurgie

IMC

Interdisziplinäre Intensivstation

Kardiologie (ITS)

Kinderkardiologie (ITS)

Alle Anzeigen

Bitte auswählen
Einsatzbereich

Verfügbarkeit

dd.mm.yyyy
Von

dd.mm.yyyy
Bis

Ort

Bundesland

Stadt
Nordrhein-Westfalen


Bitte auswählen

Position
Fachärztin/-arzt

Oberärztin/-arzt


Bitte auswählen

Art der Einrichtung
Ausblenden
Alle Einrichtungen

Krankenhaus der Grundversorgung (bis 250 Betten)

Krankenhaus der Regelversorgung (250-500 Betten)

Schwerpunktkrankenhaus (500-700 Betten)

Krankenhaus der Maximalversorgung (ab 700 Betten)

Alle Anzeigen

Bitte auswählen

Stundensatz
Anzeigen
Auf Präferenzen zurücksetzen
preferences
Empfohlene Jobs richten sich nach Ihren Qualifikationen & Präferenzen

Fachärztin/-arzt (m/w/d)
vor 11 Tagen
Anästhesiologie
06.08. - 29.08.2024
95 €/Std.
in NRW, Nordrhein-Westfalen
Fachärztin/-arzt (m/w/d)
vor 12 Tagen
Anästhesiologie
15.07. - 30.08.2024
95 €/Std.
Großraum Münster, Nordrhein-Westfalen
©2024 doctari GmbH | doctari Pflege GmbH | Version: 2.753.0
Datenschutz
Einwilligungseinstellungen
Gender-Hinweis
AGB
Impressum"
```
```{r 2024_06_24_20_20_23}
2024_06_24_20_20_23 <- "
MITGLIEDER
PORTAL
HOME PROFIL DIENSTE DOKUMENTE SGB IV 23C ABWESENHEIT DOWNLOADS
Dienstsuche Suchaufträge Dienstwünsche Dienstangebote Geplant Abgeschlossen
Dr. med. G. Schleifer
Mitglied Nr.: 16108
  
DIENSTSUCHE
 QUALIFIKATION
 GEWÜNSCHTER ORT
+ 100 km
 AUSGEWÄHLTE VORAUSSETZUNGEN
	Angestelltenverhältnis oder Praxisniederlassung nach § 23c SGB IV
	Masern-Impfschutz gemäß Gesetz
	Berufshaftpflichtversicherung
	Immunitätsnachweis COVID-19
	eigene Schutzausrüstung (Jacke, Pulli, Hose, S3-Schuhe)
	max 24 Stunden am Stück
JUNE 2024
AbwesenheitDienstwunsch
Ergebnis: 2 DiensteSortierung nach: 
Entfernung
NAW NÄHE KOTTENHEIM
2024-2728 in 48 km Entfernung
(Bereits dort gearbeitet)Nichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 30/06/2024
Beginn: 09:00 UhrDauer:
22 h 30 minEnde:
07:30 Uhr
Honorar: 40 €/h + + 25,00 € pro Einsatz
TV im Arztzimmer	Schreibtisch im Arztzimmer	Kochnische mit Wasserkocher/Mikrowelle	eigenes Waschbecken, eigene Toilette und eigene Dusche
TV im Arztzimmer	Schreibtisch im Arztzimmer	Kochnische mit Wasserkocher/Mikrowelle	eigenes Waschbecken, eigene Toilette und eigene Dusche
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Angelik Schmidt
NAW NÖRDLICH VON OLPE
2024-2659 in 64 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 28/06/2024
Beginn: 16:00 UhrDauer:
17 h 0 minEnde:
09:00 Uhr
Honorar: 35 €/h
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Celine Hassel
AGB
Impressum
Datenschutzerklärung
Notarzt-Börse
Dr. med. André Kröncke e.K.
Erlenhof, Alte Salzstr. 7
23911 Pogeez
 
Telefon: 04541 / 80180-0
Fax: 04541 / 80180-55
E-Mail: service@notarzt-boerse.de"
```

```{r 06.11.23}
06.11.23 <- "
UNSERE AKTUELLEN ANGEBOTE FÜR SIE

AKTUELL VERFÜGBARE AUFTRÄGE
Gefunden: 6 Aufträge, Sortierung: Datum aufsteigend
 
	DIENSTPLAN NEF WERDOHL NOVEMBER 2023 
2023-4020 in 69 km Entfernung	
Notarzt
 am   Mo, 06.11.2023  von 19:00 Uhr  bis 19:00 Uhr + 1d  Dauer 24 h Honorar 47 €/h	DETAILS
Verfügbare Dienstleistungen in der Unterkunft
				
				
Voraussetzungen: Angestelltenverhältnis oder Praxisniederlassung nach § 23c SGB IV Berufshaftpflichtversicherung eigene Schutzausrüstung (Jacke Pulli Hose S3-Schuhe) Masern-Impfschutz gemäß Gesetz
NAB-Wachen: NEF Werdohl: Vakante Dienste im November 2023, Nr.: 2023-4020

Liebe Notärztin, lieber Notarzt,

für unser NEF Werdohl (PLZ-Bereich 587..) benötige ich Ihre Unterstützung!
Ich suche einen Notarzt für einen letzten vakanten Dienst im November.

Mo., 06.11.23, 19 - 19 Uhr

Haben Sie Zeit und Lust, diesen Dienst zu übernehmen?

Dann freue ich mich über Ihre positive Rückmeldung und wünsche einen schönen Tag.

Bitte klicken Sie bei Interesse auf "Details" oder rufen Sie uns unter der Telefonnummer 045418018070 an um sich für den Dienst anzumelden.

 
	DIENSTPLAN NEF ALTENA DEZEMBER 2023 
2023-4025 in 69 km Entfernung	
Notarzt
 am   So, 03.12.2023  von 19:00 Uhr  bis 19:00 Uhr + 1d  Dauer 24 h Honorar 47 €/h	DETAILS
Verfügbare Dienstleistungen in der Unterkunft
					
					
Voraussetzungen: Angestelltenverhältnis oder Praxisniederlassung nach § 23c SGB IV Berufshaftpflichtversicherung eigene Schutzausrüstung (Jacke Pulli Hose S3-Schuhe) Masern-Impfschutz gemäß Gesetz
NAB-Wachen: NEF Altena: So., 03. Dezember 2023, Nr.: 2023-4025

Liebe Notärztin, lieber Notarzt,

für unser NEF Altena (PLZ-Bereich 587..) suche ich einen Notarzt für einen letzten vakanten Dienst im Dezember.

So., 03.12.23, 19 - 19 Uhr

Es erwarten Sie ca. 2 - 3 Einsätze in 24 Stunden.

Haben Sie Zeit und Lust, diesen Dienst zu übernehmen?

Dann freue ich mich über Ihre positive Rückmeldung und wünsche einen schönen Tag.

Bitte klicken Sie bei Interesse auf "Details" oder rufen Sie uns unter der Telefonnummer 045418018070 an um sich für den Dienst anzumelden.

 
	DIENSTPLAN NEF WERDOHL DEZEMBER 2023 
2023-4026 in 69 km Entfernung	
Notarzt
 am   Mo, 01.01.2024  von 19:00 Uhr  bis 19:00 Uhr + 1d  Dauer 24 h Honorar 50 €/h + Tag 1: 20 €/h	DETAILS
Verfügbare Dienstleistungen in der Unterkunft
				
				
Voraussetzungen: Angestelltenverhältnis oder Praxisniederlassung nach § 23c SGB IV Berufshaftpflichtversicherung eigene Schutzausrüstung (Jacke Pulli Hose S3-Schuhe) Masern-Impfschutz gemäß Gesetz
NAB-Wachen: NEF Werdohl: Mo., 01.01.24 Nr.: 2023-4026

Liebe Notärztin, lieber Notarzt,

für unser NEF Werdohl (PLZ-Bereich 587..) benötige ich Ihre Hilfe !
Ich suche einen Notarzt für einen vakanten Dienst im Januar.

Mo., 01.01.24, 19 - 19 Uhr

Haben Sie Zeit und Lust das Team vor Ort bei diesem Dienst zu unterstützen?

Dann freue ich mich über Ihre positive Rückmeldung und wünsche einen schönen Tag.

Bitte klicken Sie bei Interesse auf "Details" oder rufen Sie uns unter der Telefonnummer 045418018070 an um sich für den Dienst anzumelden.

 
	DIENSTPLAN NEF NEUWIED DEZEMBER 2023 
2023-4027 in 42 km Entfernung	
Notarzt
 am   So, 24.12.2023  von 19:00 Uhr  bis 08:00 Uhr + 1d  Dauer 13 h Honorar 50 €/h + Tag 1: 20 €/h + Tag 2: 20 €/h	DETAILS
Verfügbare Dienstleistungen in der Unterkunft
					
					
Voraussetzungen: Angestelltenverhältnis oder Praxisniederlassung nach § 23c SGB IV Berufshaftpflichtversicherung eigene Schutzausrüstung (Jacke Pulli Hose S3-Schuhe) Masern-Impfschutz gemäß Gesetz
NAB-Wachen: NEF Neuwied: Vaknete Dienste im Dezember 2023, Nr.: 2023-4027

Liebe Notärztin, lieber Notarzt,

für unser NEF Neuwied (PLZ-Bereich 565..) suchen wir einen Notarzt für vakante Dienste im Dezember.

So., 24.12.23, 19:00 - 08:00 Uhr
Mo., 01.01.24, 19:00 - 19:00 Uhr

Es erwarten Sie ca. 3-4 Einsätze in 24 Stunden.

Haben Sie Zeit und Lust, einen der letzten vakanten Dienste zu übernehmen?
Dann freue ich mich über Ihre positive Rückmeldung und wünsche einen schönen Tag.

Bitte klicken Sie bei Interesse auf "Details" oder rufen Sie uns unter der Telefonnummer 045418018070 an um sich für den Dienst anzumelden.

 
	NEF NÄHE WIPPERFÜRTH 
2023-4635 in 33 km Entfernung	
Notarzt
 am   Mi, 25.10.2023  von 08:00 Uhr  bis 20:00 Uhr   Dauer 12 h  Honorar 70 €/h	DETAILS
Verfügbare Dienstleistungen in der Unterkunft
Voraussetzungen: Angestelltenverhältnis oder Praxisniederlassung nach § 23c SGB IV Nachweis der DRV-Befreiung Masern-Impfschutz gemäß Gesetz
NAB: DRINGEND: NEF Nähe Wipperfürth: MORGEN, 25. Oktober 2023, Nr.: 2023-4635

Liebe Notärztin, lieber Notarzt,

für ein NEF in der Nähe von Wipperfürth (PLZ-Bereich 515..) suchen wir einen Notarzt für einen vakanten Dienst am morgigen Mittwoch.

Haben Sie Zeit und Lust uns zu helfen?

Bitte klicken Sie bei Interesse auf "Details" oder rufen Sie uns unter der Telefonnummer 04541801800 an um sich für den Dienst anzumelden.

 
	NEF NÄHE NEUSS 
2023-4669 in 55 km Entfernung	
Notarzt
 am   Do, 02.11.2023  von 16:00 Uhr  bis 07:30 Uhr + 1d  Dauer 15 h Honorar 45 €/h	DETAILS
Verfügbare Dienstleistungen in der Unterkunft
Voraussetzungen: Angestelltenverhältnis oder Praxisniederlassung nach § 23c SGB IV Masern-Impfschutz gemäß Gesetz
NAB: NEF Nähe Neuss: Do., 02. November 2023, Nr.: 2023-4669

Liebe Notärztin, lieber Notarzt,

für ein NEF in der Nähe von Neuss (PLZ-Bereich 415..) suchen wir einen Notarzt für einen vakanten Dienst im November.

Haben Sie Zeit?

Bitte klicken Sie bei Interesse auf "Details" oder rufen Sie uns unter der Telefonnummer 04541801800 an um sich für den Dienst anzumelden.

Sie erhalten diese Email, da Sie sich als Arzt bei der Notarzt-Börse registriert haben. Möchten Sie heute keine Emails mehr erhalten, dann melden Sie sich bitte hier ab.

Notarzt-Börse
Dr. med. Andre Kröncke
Erlenhof - alte Salzstraße 7, 23911 Pogeez

Tel: 04541 80180-0
Fax: 04541 80180-55
info@notarzt-boerse.de
www.notarzt-boerse.de

Impressum
Datenschutz
AGB"
```


